dist: focal
language: php

php:
  - 8.0

# Make sure we have a recent version of docker.
addons:
  apt:
    packages:
      - docker-compose

before_script:
  # Ensure the PHP environment is ready.
  - phpenv rehash

script:
  # Get docker information.
  - docker version
  - docker-compose version

  # Validate the composer files.
  - composer validate

  # PHP linting
  - test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l

  # Build local image.
  - make

  # Create the site and mysql containers.
  - docker-compose -f tests/docker-compose.yml up -d

  # Dump some information about the created containers.
  - docker ps -a

  # Wait a bit for mysql to be ready.
  - sleep 10

  # Check coding standards (after installing phpcs)
  - docker exec -it -w /srv/www starterkit-travis-site composer install
  - docker exec -it -w /srv/www starterkit-travis-site phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - docker exec -it -u appuser -w /srv/www starterkit-travis-site phpcs -p --report=full --standard=phpcs.xml ./html/modules/custom
  - docker exec -it -u appuser -w /srv/www starterkit-travis-site phpcs -p --report=full --standard=phpcs.xml ./html/themes/custom

  # Install the site with the existing config.
  - docker exec -it starterkit-travis-site drush -y si --existing-config

after_success:
  - echo "The tests completed without errors."

after_failure:
  - echo "The tests failed. Please check the output above for problems."
  - docker exec -it starterkit-travis-site drush watchdog:show --extended
